#supper user permission given by travis
sudo: required
services:
  - docker
before_install:
  - docker build -t samrika26/Py_travis .
#travis ci understand we need python preinstalled
language: python
python:
  - "3.8"
install:
  - pip install Flask
  - pip install flask_restful
  - pip install gunicorn 
# command to install dependencies

# command to run tests
script: 
   - python main.py
   - docker run samrika26/Py_travis python main.py

after_success:
  - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password--stdin
  - docker push samrika26/Py_travis
