#supper user permission given by travis
sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t samrika26/py_travis .
#travis ci understand we need python preinstalled
language: python
python:
  - "3.8"
install:
  - pip install Flask
  - pip install flask_restful
  - pip install .
# command to install dependencies

# command to run tests
script: 
   - python -m pytest -v


after_success:
  - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password--stdin
  - docker push samrika26/py_travis
