#supper user permission given by travis
sudo: required
language: python
python:
  - "3.8"
services:
  - docker
before_install:
  - docker build -t samrika26/py2_travis .
#travis ci understand we need python preinstalled

install:
  - pip3 install -r requirements.txt
# command to install dependencies

# command to run tests
script:
 - echo 5

# command to install dependenci


after_success:
  - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password--stdin
  - docker push samrika26/py2_travis

deploy:   
        provider: script
        script: 
               docker push samrika26/flask_app22:v2;
               docker push registry.heroku.com/$HEROKU_APP/web;
               heroku container:release web --app $HEROKU_APP
        on:
          branch: main


