#supper user permission given by travis
sudo: required
#travis ci understand we need python preinstalled
language: python
python:
  - "3.8"
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies

# command to run tests
script: python main.py
