#supper user permission given by travis
sudo: required
#travis ci understand we need python preinstalled
language: python
python:
  - "3.8"
install:
  - pip install Flask
  - pip install flask_restful
# command to install dependencies

# command to run tests
script: python main.py
