apiVersion: apps/v1
kind: Deployment
metadata:
  name: pywebapp-deployment
  labels:
    app: pywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pywebapp
  template:
    metadata:
      name: pywebapp-pod
      labels:
         app: pywebapp
    spec:
        containers:
        - name: python-app-container
          image: samrika26/python_app12:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5001
          

